### ISSUE TITLE
Unexpectedly found nil

### ISSUE THREAD

**Issue by hmdalmulim** [BadhanGanesh/BJOTPViewController#13]
after received OTP i got 
BJOTPViewController/BJOTPViewController.swift:305: Fatal error: Unexpectedly found nil while implicitly unwrapping an Optional value

 @objc public var authenticateButtonTitle: String = "AUTHENTICATE" {
        willSet {
            self.authenticateButton.setTitle(newValue, for: .normal)
        }
    }
and App was stopped

**Comment by BadhanGanesh-HappyFox** [comment]
@hmdalmulim Thanks for reporting. This will be fixed in the next release - v2.6.0.

**Edit:** The issue is fixed in the above-mentioned release. LIVE now.
